### ISSUE TITLE
How to expand a cell programatically?

### ISSUE THREAD

**Issue by hdoria** [innovian/HVTableView#17]
I have a "+" button used to add new rows to my tableview. It's working fine. The code is something like:

``` swift
self.tableView.beginUpdates()
self.tableView.insertRowsAtIndexPaths([indexPath], withRowAnimation: UITableViewRowAnimation.Automatic)
self.tableView.endUpdates()
```

Now, i need to insert this row and make them expanded by default. How can I do this? I'm trying this, but it does not works very well:

``` swift
let cell = self.tableView.cellForRowAtIndexPath(indexPath)
self.tableView(self.tableView, expandCell: cell, withIndexPath: indexPath)
```

**Comment by xerxes235** [comment]
Please send me your xcode project.

**Comment by KevinJue** [comment]
Hello, 

What about this issus
I'm actually looking to do the same work, expand my first cell by default 

did you find a solution ?

**Comment by xerxes235** [comment]
Check the new version 0.2.0. We have implemented new methods to programmatically expand/collapse/toggle cells.

Check the new readme file.
