### ISSUE TITLE
Expand/collapse flicks my tableview

### ISSUE THREAD

**Issue by hdoria** [innovian/HVTableView#18]
Hi,

I'm having some trouble with HVTableView. I don't know the reason, but my tableView seems to flick every time I expand/collapse a row. The animation is very ugly. 

Take a look at the image below. You can see that some rows do not have a nice animation effect.

![untitled](https://cloud.githubusercontent.com/assets/73786/7556787/295077da-f756-11e4-8bd7-a7f720185549.gif)

Do you have any suggestions on how can I make it better?

Sample project:
https://github.com/hdoria/expandTableView

**Comment by xerxes235** [comment]
Hi,

Can you send me the Xcode project?

**Comment by hdoria** [comment]
It's here: https://github.com/hdoria/expandTableView

**Comment by xerxes235** [comment]
I checked your project; there no problem with it. Please test it on a real device; simulator usually performs animations with lower performance.

**Comment by hdoria** [comment]
The same happens on device. When i touch row 4, for example, I can see others rows blink. After some time touching the rows, all starts to blink, as if the tableView is reloading.

**Comment by hdoria** [comment]
Here's the project running on a real device. Look like other rows blink and flicks when we touch row 5/6:

![untitled1 mov](https://cloud.githubusercontent.com/assets/73786/7559806/6dcaf52a-f792-11e4-9826-6bd955531419.gif)

**Comment by xerxes235** [comment]
Yes I saw it. I didn't happen in the project's example. I will work on it asap.

**Comment by hdoria** [comment]
Thank. I appreciate. Do you have any tips? I could help you on this.

**Comment by hdoria** [comment]
Hey man, do you need help here?

**Comment by xerxes235** [comment]
check the new version 0.2.0.
