### ISSUE TITLE
is there anyway to expand only cell at a time? if a cell is already expanded, and user tries to expand another cell, the first cell should be collapsed and the new cell should be expanded

### ISSUE THREAD

**Issue by Rj707** [innovian/HVTableView#19]

**Comment by xerxes235** [comment]
Yes there's an expandOnlyOneCell property for the HVTableView which you can set it to true. You will get only one cell expanded at the same time.

**Comment by Rj707** [comment]
Thanks, I got that point from your sample project, where you have put some
documentation before code.

**Comment by Rj707** [comment]
I need your help in another library, ill b very thankful to you, if you
could. I wan the same behaviour(expanding only one cell at a time) for
vppdropdown, so tell me whats the logic behing expanding only one cell. Its
urgent. And thanks once again

**Comment by xerxes235** [comment]
It's easy; HVTableView collapses the recent expanded cell and expands a new one

**Comment by Rj707** [comment]
AOA Hamid!
                    i have a question. is there a way to navigate to  the
other view controller when clicking on collapsed/expanded cell. as
HVTableView didselectrowatindexpath method expands/collapses the cell.
Thanks

**Comment by xerxes235** [comment]
Create a UITapGestureRecognizer for the cell.contentView. By capturing the taps from the cell with a gesturerecognizer, the default didSelectRowAtIndexPath won't be called. You can push the new vc from that event.
