### ISSUE TITLE
Crash - When a cell is left expanded, you update the number of rows and select a different cell

### ISSUE THREAD

**Issue by creatd** [innovian/HVTableView#4]
First of all, thank you very much for this, really useful.

Scenario
- Table has 5 rows
- You expand the 5th row
- You reload data so the table now has 2 rows
- You select the 1st row
- You get a crash because it's trying to delete the previously expanded 5th row, which is out of bounds now

My workaround was to implement a 
- (void)collapseExpandedCells;
  method which I call before changing the data source of the table

I've implemented it as follows
- (void)collapseExpandedCells {
  [expandedIndexPaths removeAllObjects];
  
  selectedIndexPath = nil;
  
  [self performSelectorOnMainThread:@selector(reloadData) withObject:nil waitUntilDone:YES];

}

Cheers,
Ege

**Comment by bb-git** [comment]
I can still reproduce this crash in 2016, how is this possible?

**Comment by xerxes235** [comment]
Unfortunately we have not supported adding new rows to the HVTableView for now. sorry for the inconvenience .
